import type { Metadata } from "next";
import type { ReactNode } from "react";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import Footer from "@/components/layout/footer";
import { ThemeProvider } from "@/providers/theme-provider";



export const metadata: Metadata = {
  title: "Cosmo Comickon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="pt" suppressHydrationWarning>
      <body className="w-screen min-h-screen h-auto flex-col flex justify-between overflow-x-hidden">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <div className="w-full h-fit flex flex-col gap-[2.5vw]">{children}</div>
          <Footer />
        </ThemeProvider>

      </body>
    </html>
  );
}
